sudo: false
language: generic

cache:
  apt: true

os: linux
dist: trusty

matrix:
  include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - make test
